### ISSUE TITLE
Chapter: Getting started with exercises

### ISSUE THREAD

**Issue by rauschma** [rauschma/exploring-js#2]
(I deleted comments that reported issues that are fixed now.)

**Comment by Essential** [comment]
Small typos in README.txt

```text
  cd impatient-js-code/
  npm install
  ```
What is `text` ?

Then,

```text
  npm t installation_test.js
  ```

should be `npm test`

**Comment by rauschma** [comment]
@Essential:
* The `text` is Markdown. But you are right in that it may confuse some people. I’ll omit it in the next release.
* The command should work as it is. `npm t` is short for `npm test` and the filename is required, because this is about running a single test.

**Comment by Essential** [comment]
@rauschma The alias is not really beginner-friendly, imo ; and I'm not sure yarn users have this alias.

**Comment by Ngugi1** [comment]
Small typo:

Page 77,
Getting Started With Quizzes and Exercises,
First Paragraph, Last Sentence, Last word should read: **them** not **theem**

**Comment by rauschma** [comment]
@Ngugi1 Thanks, fixed now!

**Comment by matt-wiese** [comment]
Hey @rauschma 
I'm encountering an error when trying to use/configure AVA in Atom and I'm reaching out here as AVA is referencing your package.json in ./impatient-js-code 2020-06-23;
_______
> @ test C:\Users\c-matt.wiese\Google Drive\JS\impatient-js-code 2020-06-23
> ava --verbose --match "!*#bonus" "installation_test.mjs"


  **× Enhancement compilation must be configured in AVA’s Babel options.**
npm ERR! Test failed.  See above for more details.
_______
I've used npm to install esm, babel, http-server, and isisomorphic-fetch. Please help!

**Comment by rauschma** [comment]
@matt-wiese: It does work if you run npm from a terminal app, right?

Alas, my knowledge of AVA is limited. It looks like you are running an older version – IIRC, enhancement compilation was something that older versions did/required: https://github.com/avajs/ava/issues/2376

If that’s not it, you may have to ask the AVA team.

**Comment by matt-wiese** [comment]
> @matt-wiese: It does work if you run `npm t` from a terminal app, right?
> 
> Alas, my knowledge of AVA is limited. It looks like you are running an older version – IIRC, enhancement compilation was something that older versions did/required: [avajs/ava#2376](https://github.com/avajs/ava/issues/2376)
> 
> If that’s not it, you may have to ask the AVA team.

yep that's what I tried running as well. And FWIW I am on Win10 so I'm using Atom for a terminal app. Node JS is installed, ran through the simple ava install available from their repo. I am using AVA v3.14

**Comment by rauschma** [comment]
@matt-wiese: What happens if you do the following in a normal terminal:

* Download the exercises
* Install AVA locally via `npm install` inside the unpacked directory with the exercises
* Invoke `npm t` for an exercise

Does that work or not?

**Comment by matt-wiese** [comment]
> @matt-wiese: What happens if you do the following in a normal terminal:
> 
> * Download the exercises
> * Install AVA locally via `npm install` inside the unpacked directory with the exercises
> * Invoke `npm t` for an exercise
> 
> Does that work or not?

I performed these steps exactly and it seems each .mjs had an uncaught exception or error thrown in test

**Comment by rauschma** [comment]
> I performed these steps exactly and it seems each .mjs had an uncaught exception or error thrown in test

That is expected (as long as it’s: “missing module” and “comparison failed”) – the exercises are about making these exceptions go away.

The one test that should succeed, is:

```
npm t installation_test.mjs
```

**Comment by BehdadEs** [comment]
Hey @rauschma,
I wanted to test exercise files and followed the instructions in README but when I try to test the codes with installation_test.mjs I get this message:
`Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'assert' imported from D:\JS\exercies\installation_test.mjs
    at packageResolve (internal/modules/esm/resolve.js:655:9)
    at moduleResolve (internal/modules/esm/resolve.js:696:18)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:810:11)
    at Loader.resolve (internal/modules/esm/loader.js:86:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:230:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:56:40)
    at link (internal/modules/esm/module_job.js:55:36)
npm ERR! Test failed.  See above for more details.`

**Comment by rauschma** [comment]
@BehdadEs:
* This is the ES2020 edition, right?
* `npm install` went well, I take it?
* What’s the output if you run `node -v`

**Comment by BehdadEs** [comment]
@rauschma 
No, I'm learning fron ES2021 editions
`npm install` went well with no issues I think
npm install output:
```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 125 packages from 83 contributors and audited 126 packages in 2.527s

18 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```
`node -v` outpu: 6.14.11

**Comment by rauschma** [comment]
> `node -v` output: 6.14.11

OK, that’s the problem:
* You need a version of node that’s at least 15.5.1 (see `README.txt`)
* You can download an installer here: https://nodejs.org/

**Comment by BehdadEs** [comment]
> > `node -v` output: 6.14.11
> 
> OK, that’s the problem:
> 
> * You need a version of node that’s at least 15.5.1 (see `README.txt`)
> * You can download an installer here: https://nodejs.org/

It worked!
I was using TLS version and didn't pay attention to the version number .
Thanks

**Comment by smith558** [comment]
@rauschma there is a mistake in the text in the paragraph:

> As for the other lines:
> 
> The comment at the very beginning shows the shell command for running the test.
> Line A: We import the Node.js assertion library (in strict assertion mode).
> Line B: We import the function to test.
> Line C: We define a test. This is done by calling the function test():
> First parameter: the name of the test.
> Second parameter: the test code, which is provided via an arrow function. The parameter t gives us access to AVA’s testing API (assertions, etc.).

in the section https://exploringjs.com/js/book/ch_exercises.html#part-2-the-tests

The paragraph is referring to the AVA testing framework, yet the code and the rest of the text talk about Mocha

**Comment by anandthunder** [comment]
dr. rauschma please can you show me where is the .zip file to download i cannot locate it?
