### ISSUE TITLE
Chapter: Asynchronous programming in JavaScript

### ISSUE THREAD

**Issue by rauschma** [rauschma/exploring-js#26]

**Comment by AndiPersti** [comment]
39.1.3 Callback-based asynchronous functions :

In the code snippet the second parameter of the callback is named `result`. But later on in the text, the parameter is called `r`:
> A result `r`: Then the following task is added to the queue.
>   `taskQueue.enqueue(() => callback(null, r));`

I'd suggest to use `result` in both places.

**Comment by rauschma** [comment]
@AndiPersti True, thanks! Fixed in next release.

**Comment by 0fye** [comment]
In 39.2 "The call stack" section:

https://exploringjs.com/impatient-js/ch_async-js.html#the-call-stack

`Error.prototype.stack` is non-standard:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/Stack

It's implemented in all platforms though. Maybe mention this fact a little bit?

**Comment by rauschma** [comment]
@0fye Yes! Mentioned here: https://exploringjs.com/impatient-js/ch_exception-handling.html#error-stack

**Comment by 0fye** [comment]
Ahh nice, thanks!!! @rauschma

**Comment by atengberg** [comment]
As I've said before thank you for such tremendous educational resource(s)!

Is there a reason there is no mention of AbortController? As a standard mechanism in the browser and apparently even server side js, and as not much would need to be added--as complete as the rest of the book is, a paragraph example would seem to fit well with the rest of the async content?

Also in a previous issue you give reference to an async queue implementation; perhaps consider redrafting as an extra (supplemental?) subchapter, as such a (without library dependency) model, would be a good way to demonstrate culmination of chapters and provide a very useful example as far as something that could be used to bridge to next level of JavaScript mastery. 

To that end, perhaps your next book in the series could be along the lines of optimal approach to software/project architecture for either JS-TS-node?

Thanks again for such well written educational material. Really could be a "gold" standard for genuine text-book quality.

**Comment by smith558** [comment]
@rauschma the following example in https://exploringjs.com/js/book/ch_async-js.html#the-call-stack is wrong:
```
Error
    at h (demos/async-js/stack_trace.mjs:2:17)
    at g (demos/async-js/stack_trace.mjs:7:3)
    at f (demos/async-js/stack_trace.mjs:10:3)
    at demos/async-js/stack_trace.mjs:12:1
```

As noted ("Note that it records where calls were made, not return locations."), It should actually be:
```
Error
    at h (demos/async-js/stack_trace.mjs:2:17)
    at g (demos/async-js/stack_trace.mjs:6:3)
    at f (demos/async-js/stack_trace.mjs:9:3)
    at demos/async-js/stack_trace.mjs:11:1
```

**Comment by smith558** [comment]
@rauschma in the section https://exploringjs.com/js/book/ch_async-js.html#resources, the video “Help, I'm stuck in an event-loop” by Philip Roberts is not public on Vimeo anymore, I suggest replacing it with the version on YouTube (https://www.youtube.com/watch?v=6MXRNXXgP_0).
