### ISSUE TITLE
NPM Test Fails

### ISSUE THREAD

**Issue by pertrai1** [rauschma/exploring-js#53]
I purchased the book and downloaded the code. After following the `README` file, I get the following:

```
$ npm t exercises/arrays/convert_to_numbers_test.mjs

> @ test C:\Users\rsimpson\Desktop\impatient-js-code 2021-06-23
> mocha --ui qunit --invert --fgrep "#bonus" "exercises/arrays/convert_to_numbers_test.mjs"


Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'C:\...\impatient-js-code 2021-06-23\node_modules\assert\strict' imported from C:\...\impatient-js-code 2021-06-23\exercises\arrays\convert_to_numbers_test.mjs
    at finalizeResolution (internal/modules/esm/resolve.js:276:11)
    at moduleResolve (internal/modules/esm/resolve.js:699:10)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:810:11)
    at Loader.resolve (internal/modules/esm/loader.js:85:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:229:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:51:40)
    at link (internal/modules/esm/module_job.js:50:36)
npm ERR! Test failed.  See above for more details.
```

```
$ node -v
v14.15.1

$ npm -v
6.14..8
```

**Comment by rauschma** [comment]
@pertrai1 You need at least Node.js v15.5.0. You should have gotten a warning when running `installation_test.mjs` (see README).

**Comment by pertrai1** [comment]
@rauschma I am so sorry I did not even notice that the version was switched in my terminal.
